apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radius-performance-demo
resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-init-configmap.yaml
  - mysql.yaml
  - catalog-configmap.yaml
  - catalog-api.yaml
  - prometheus-configmap.yaml
  - prometheus.yaml
